### ISSUE TITLE
Use numpy random Generator for random numbers

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-addon-sqd#52]
### What should we add?

Changing the global random state like this is discouraged:
https://github.com/Qiskit/qiskit-addon-sqd/blob/7ddfb2101c7f2cefb75f06340dfbf42f5c6cc080/qiskit_addon_sqd/configuration_recovery.py#L213

Instead, a Generator object should be initialized using `np.random.default_rng(seed)` and used.

**Comment by caleb-johnson** [comment]
> ### What should we add?
> 
> Changing the global random state like this is discouraged:
> 
> https://github.com/Qiskit/qiskit-addon-sqd/blob/7ddfb2101c7f2cefb75f06340dfbf42f5c6cc080/qiskit_addon_sqd/configuration_recovery.py#L213
> 
> 
> 
> Instead, a Generator object should be initialized using `np.random.default_rng(seed)` and used.

I believe Generators are a py312 addition? I think we need to use the old random behavior for backward compatibility.

**Comment by caleb-johnson** [comment]
> ### What should we add?
> 
> Changing the global random state like this is discouraged:
> 
> https://github.com/Qiskit/qiskit-addon-sqd/blob/7ddfb2101c7f2cefb75f06340dfbf42f5c6cc080/qiskit_addon_sqd/configuration_recovery.py#L213
> 
> 
> 
> Instead, a Generator object should be initialized using `np.random.default_rng(seed)` and used.

When I looked at this before, rustowrkx, qiskit, matplotlib, and scipy all had numpy<2.0 pinned. We cant use Generators until they all support it

**Comment by kevinsung** [comment]
Generator has been around since at least Numpy 1.17: https://numpy.org/doc/1.17/reference/random/generator.html

**Comment by kevinsung** [comment]
The way the same integer seed is passed around in the [chemistry tutorial](https://qiskit.github.io/qiskit-addon-sqd/tutorials/01_chemistry_hamiltonian.html#Iteratively-refine-the-samples-using-configuration-recovery-and-approximate-the-ground-state-at-each-iteration) might be statistically invalid. Again, a single Generator instance should be created and passed instead.

**Comment by kevinsung** [comment]
An integer seed is used to set the internal state of a pseudo-random number generator (PRNG). If the same seed is used at two different points in time, then the PRNG will have the same internal state at those different points in time, and its results won't be statistically independent.

>All it does is fix the randomness for each of these functions to make things deterministic.

The performance of SQD relies on the random numbers drawn at different points of time being statistically independent. While seeding is needed to make results deterministic, care needs to be taken when seeding to ensure that the results are statistically valid.

**Comment by caleb-johnson** [comment]
> An integer seed is used to set the internal state of a pseudo-random number generator (PRNG). If the same seed is used at two different points in time, then the PRNG will have the same internal state at those different points in time, and its results won't be statistically independent.
> 
> > All it does is fix the randomness for each of these functions to make things deterministic.
> 
> The performance of SQD relies on the random numbers drawn at different points of time being statistically independent. While seeding is needed to make results deterministic, care needs to be taken when seeding to ensure that the results are statistically valid.

Cool, that makes sense. Avoiding global variables is almost always a good thing

**Comment by kevinsung** [comment]
>Avoiding global variables is almost always a good thing

It's not that the variable is global, it's that it's an integer, which resets the PRNG to the same state every time. Instead of an integer, it should be a Generator object, which will be used directly without having its state reset. So it's more like, you should have a single Generator object that's initialized once globally and used everywhere.
