### ISSUE TITLE
In chemistry tutorial, sample from circuit instead of generating random samples

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit-addon-sqd#81]
### What should we add?

The [chemistry tutorial](https://qiskit.github.io/qiskit-addon-sqd/tutorials/01_chemistry_hamiltonian.html#Step-3:-Execute-experiments) runs SQD on uniformly random bitstrings. It would be more interesting to sample from the actual circuit with a basic noise model. In ffsim 0.0.46, FfsimSampler supports global depolarizing noise.

**Comment by caleb-johnson** [comment]
For now we will stick with showing the Runtime Sampler in a comment and generate random samples. We may want to do a guide on the LUCJ circuit, and I think we could use this to sample from the circuit in that guide
